name: Deploy Flask App

on:
  push:
    branches:
      - main  # Kích hoạt workflow khi có thay đổi trên nhánh main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Bước 1: Checkout mã nguồn từ repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Bước 2: Đăng nhập vào Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Thêm Docker username vào GitHub Secrets
          password: ${{ secrets.DOCKER_PASSWORD }}  # Thêm Docker password vào GitHub Secrets

      # Bước 3: Thiết lập Docker Buildx (nếu cần cho kiến trúc đa nền tảng)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Bước 4: Xây dựng hình ảnh Docker
      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64  # Xác định kiến trúc hình ảnh (có thể thay đổi nếu cần)
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/flask-app:v1
            ${{ secrets.DOCKER_USERNAME }}/flask-app:latest

      # Bước 5: Đẩy hình ảnh lên Docker Hub
      - name: Push Docker image to Docker Hub
        uses: docker/build-push-action@v5
        with:
          push: true
